version: '3.9'

services:
  app:
    build: ./
    command: sh -c "sh wait-db.sh && ./app"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - minio
    networks:
      - devdzen

  minio:
    image: minio/minio
    command: minio server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    networks:
      - devdzen

  db:
    restart: on-failure
    image: postgres:latest
    ports:
      - "5436:5432"
    env_file:
      - .env
    volumes:
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    networks:
      - devdzen

networks:
  devdzen:
    driver: bridge

volumes:
  minio_data:
  pg_data: