version: '3.9'

services:
  image-box-app:
    build: ./
    command: ./scripts/database/wait-db.sh db ./image-box-app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
        - "5436:5432"
    volumes:
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql
