version: '3.9'

services:
  image-box-app:
    build: ./
    command: sh -c "sh wait-db.sh && ./image-box-app"
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

#  minio:
#    image: minio/minio
#    command: server /data
#    ports:
#      - "9000:9000"
#    env_file:
#      - .env
#    volumes:
#      - minio_data:/data

  db:
    restart: always
    image: postgres:latest
    ports:
        - "5436:5432"
    env_file:
      - .env
    volumes:
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data

#networks:
#  mynetwork:
#    driver: bridge

volumes:
  minio_data:
  pg_data: