basePath: /
host: localhost:8080
info:
  contact: {}
  description: rvinnie's ChatGPT server.
  title: GPT API
  version: "1.0"
paths: {}
securityDefinitions:
  UsersAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
